name: PlatformIO CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install development tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-format

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

  compile-firmware:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [esp32dev-ci]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Create dummy credentials file
      run: |
        echo "[ota_credentials]" > platformio_credentials.ini
        echo "upload_port = 0.0.0.0" >> platformio_credentials.ini
        echo "auth_password = dummy" >> platformio_credentials.ini

    - name: Build environment
      run: pio run -e ${{ matrix.environment }}
